import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { RegistryService } from "../src/server/service";
import { LocalStore } from "../src/server/store";
import { calculatePreScore } from "../src/server/scoring/engine";
import { loadConfig } from "../src/server/scoring/config";
import { ApplicationError } from "../src/server/errors";
import { importOfficial, literal, official, OFFICIAL_CHECKSUM, synthetic, tempStore } from "./helpers";
import { sha256 } from "../src/server/identity";
import type { ScoreSnapshot } from "../src/server/domain";

let temporary: ReturnType<typeof tempStore>;
beforeEach(() => { temporary = tempStore(); });
afterEach(() => { temporary.cleanup(); });
describe("BE-REQ-01/02/03: integrated registry → selected card → partial PRE-SCORE", () => {
  it("persists original bytes, six isolated cards and sources; only the opened process is scored", async () => {
    const scorer = vi.fn(calculatePreScore);
    const service = new RegistryService(temporary.store, loadConfig, scorer);
    const registry = importOfficial(service);
    expect(registry.canContinue).toBe(true); expect(registry.selectableProcesses).toHaveLength(6);
    expect(scorer).not.toHaveBeenCalled();
    expect(temporary.store.readOriginal(registry.registryVersionId)).toEqual(official());
    const processId = registry.selectableProcesses[0].processId;
    const opened = service.openProcess(processId);
    expect(opened.view).toMatchObject({ scoreProcessing: { state: "PENDING" }, activeScoreSnapshot: null });
    expect(service.openProcess(processId).job).toBeNull();
    await service.runScore(opened.job!);
    const card = service.readProcess(processId);
    expect(card.scoreProcessing.state).toBe("AVAILABLE");
    expect(card.activeScoreSnapshot).toMatchObject({ stage: "PRE_SCORE", methodologyVersion: "1.1", value: { knownSum: 3, fullScore: null, range: [6, 18] } });
    expect(service.openProcess(processId).view.activeScoreSnapshot?.scoreSnapshotId).toBe(card.activeScoreSnapshot?.scoreSnapshotId);
    expect(service.openProcess(processId).job).toBeNull();
    const db = temporary.store.read();
    expect(Object.values(db.processes).filter(p => p.attempts.length)).toHaveLength(1);
    expect(db.processes[processId].inputSnapshots).toHaveLength(1);
    expect(db.processes[processId].scoreSnapshots).toHaveLength(1);
    expect(scorer).toHaveBeenCalledTimes(1);
    const derivedId = db.processes[processId].scoreSnapshots[0].sourceReferences[0].sourceReferenceId;
    const derived = service.readSource(derivedId);
    expect(derived).toMatchObject({ sourceType: "calculated", factStatus: "Derived", excerptOrValue: 48 });
    const inputSource = service.readSource(derived.derivation!.inputSourceReferenceIds[0]);
    expect(inputSource).toMatchObject({ sourceType: "registry", factStatus: "Confirmed", coordinate: "L9" });
    expect(db.audit.map(e => e.type)).toEqual(expect.arrayContaining(["REGISTRY_UPLOADED", "SHEET_PROCESSED", "INPUT_SNAPSHOT_CREATED", "SCORE_PENDING", "SCORE_RUNNING", "SCORE_AVAILABLE"]));
    expect(sha256(official())).toBe(OFFICIAL_CHECKSUM);
    const restarted = new RegistryService(new LocalStore(temporary.directory));
    expect(restarted.openProcess(processId).job).toBeNull();
    expect(restarted.readProcess(processId)).toEqual(card);
  });
  it("scores the explicit PROCESS row 14 from shared-formula caches and retains provenance after restart", async () => {
    const service = new RegistryService(temporary.store);
    const registry = importOfficial(service);
    const db = temporary.store.read();
    const row = db.registries[registry.registryVersionId].sheets["Лист3"].rows.find(r => r.excelRowNumber === 14)!;
    const process = Object.values(db.processes).find(p => p.sourceRowId === row.sourceRowId)!;
    expect(registry.selectableProcesses.some(p => p.processId === process.processId)).toBe(true);
    const opened = service.openProcess(process.processId);
    expect(opened.view.scoreProcessing.state).toBe("PENDING");
    await service.runScore(opened.job!);
    const card = service.readProcess(process.processId);
    expect(card.scoreProcessing.state).toBe("AVAILABLE");
    const snapshot = card.activeScoreSnapshot!;
    expect(snapshot.value.criteria.map(c => c.score)).toEqual([5, 5, null, null, null]);
    expect(snapshot.value).toMatchObject({ knownSum: 10, fullScore: null, coverage: 0.4, range: [13, 25] });
    expect(snapshot.feasibility.criteria.every(c => c.score === null)).toBe(true);
    const stored = temporary.store.read().processes[process.processId];
    expect(stored.scoreSnapshots[0].derivedFacts).toEqual(expect.arrayContaining([expect.objectContaining({ field: "annual_labor_hours", value: 25200 })]));
    const restored = new RegistryService(new LocalStore(temporary.directory));
    expect(restored.openProcess(process.processId).job).toBeNull();
    expect(restored.readProcess(process.processId)).toEqual(card);
    const source = stored.sourceReferences.find(s => s.coordinate === "K14")!;
    expect(restored.readSource(source.sourceReferenceId)).toMatchObject({ cachedValue: 17.5, factStatus: "Confirmed", formulaMetadata: { sharedIndex: "0", masterCoordinate: "K13", groupRef: "K13:L14" } });
    expect(card.dataQualityIssues.filter(i => i.code === "FORMULA_REFERENCE_OUTSIDE_TABLE")).toHaveLength(2);
  });
  it("publishes RUNNING and prevents duplicate jobs while a calculation is in flight", async () => {
    let release!: (result: ScoreSnapshot) => void;
    const scorer = vi.fn(() => new Promise<ScoreSnapshot>(resolve => { release = resolve; }));
    const service = new RegistryService(temporary.store, loadConfig, scorer);
    const processId = importOfficial(service).selectableProcesses[0].processId;
    const { job } = service.openProcess(processId);
    const running = service.runScore(job!);
    expect(service.readProcess(processId).scoreProcessing.state).toBe("RUNNING");
    expect(service.openProcess(processId).job).toBeNull();
    expect(service.retryScore(processId).job).toBeNull();
    await service.runScore(job!);
    expect(scorer).toHaveBeenCalledTimes(1);
    release(calculatePreScore(temporary.store.read().processes[processId].inputSnapshots[0]));
    await running;
    expect(service.readProcess(processId).scoreProcessing.state).toBe("AVAILABLE");
  });
  it("keeps card/DQ after failure, requires explicit retry, retains attempts and reuses frozen input", async () => {
    let fail = true;
    const service = new RegistryService(temporary.store, loadConfig, snapshot => {
      if (fail) throw new Error("private stack and internal failure");
      return calculatePreScore(snapshot);
    });
    const registry = importOfficial(service), processId = registry.selectableProcesses[0].processId;
    const { job, view } = service.openProcess(processId);
    await service.runScore(job!);
    const failed = service.readProcess(processId);
    expect(failed.scoreProcessing).toMatchObject({ state: "FAILED", error: { code: "INTERNAL_ERROR", retryable: true } });
    expect(JSON.stringify(failed)).not.toContain("private stack");
    expect(failed.processName).toBe(view.processName); expect(failed.dataQualityIssues).toEqual(view.dataQualityIssues);
    expect(failed.activeScoreSnapshot).toBeNull(); expect(service.readRegistry(registry.registryVersionId)).toEqual(registry);
    expect(service.openProcess(processId).job).toBeNull();
    fail = false;
    const retry = service.retryScore(processId); expect(retry.view.scoreProcessing.state).toBe("PENDING");
    expect(service.retryScore(processId).job).toBeNull();
    await service.runScore(retry.job!);
    expect(service.readProcess(processId).scoreProcessing.state).toBe("AVAILABLE");
    const record = temporary.store.read().processes[processId];
    expect(record.attempts.map(a => a.state)).toEqual(["FAILED", "AVAILABLE"]); expect(record.inputSnapshots).toHaveLength(1); expect(record.scoreSnapshots).toHaveLength(1);
  });
  it("backend rejects a non-retryable failure retry", async () => {
    const service = new RegistryService(temporary.store, () => { throw new ApplicationError("INCOMPLETE_SCORING_SPEC", "Конфигурация неполна.", 422); });
    const processId = importOfficial(service).selectableProcesses[0].processId;
    await service.runScore(service.openProcess(processId).job!);
    expect(service.readProcess(processId).scoreProcessing.error?.retryable).toBe(false);
    expect(() => service.retryScore(processId)).toThrow(expect.objectContaining({ code: "RETRY_NOT_ALLOWED" }));
    expect(service.openProcess(processId).job).toBeNull();
  });
  it("marks interrupted scoring FAILED on restart and allows an explicit retry", async () => {
    const service = new RegistryService(temporary.store);
    const processId = importOfficial(service).selectableProcesses[0].processId;
    service.openProcess(processId);
    const restored = new RegistryService(new LocalStore(temporary.directory));
    expect(restored.readProcess(processId).scoreProcessing).toMatchObject({ state: "FAILED", error: { code: "PROCESSING_INTERRUPTED", retryable: true } });
    expect(restored.openProcess(processId).job).toBeNull();
    await restored.runScore(restored.retryScore(processId).job!);
    expect(restored.readProcess(processId).scoreProcessing.state).toBe("AVAILABLE");
  });
  it("withdraws old selections, discards stale processing runs, and restores same-sheet identities", () => {
    const service = new RegistryService(temporary.store), registry = importOfficial(service);
    const old = service.selectSheet(registry.registryVersionId, "10_МЛХ");
    expect(old.view).toMatchObject({ state: "READING", canContinue: false, selectableProcesses: [] });
    const latest = service.selectSheet(registry.registryVersionId, "Цифра");
    service.processSheet(registry.registryVersionId, old.runId);
    expect(service.readRegistry(registry.registryVersionId)).toMatchObject({ selectedSheet: "Цифра", state: "READING", selectableProcesses: [] });
    service.processSheet(registry.registryVersionId, latest.runId);
    expect(service.readRegistry(registry.registryVersionId)).toMatchObject({ state: "ERROR", canContinue: false, selectableProcesses: [] });
    const back = service.selectSheet(registry.registryVersionId, "Лист3"); service.processSheet(registry.registryVersionId, back.runId);
    expect(service.readRegistry(registry.registryVersionId).selectableProcesses).toEqual(registry.selectableProcesses);
    expect(Object.keys(temporary.store.read().processes)).toHaveLength(6);
  });
  it("does not derive canContinue from individual ERROR severity", async () => {
    const service = new RegistryService(temporary.store);
    const meta = service.upload(synthetic({ rows: { 9: literal("D9", "Тест") + literal("K9", "1/24") + literal("L9", 12) } }), "fixture.xlsx");
    const run = service.selectSheet(meta.registryVersionId, "Лист3"); service.processSheet(meta.registryVersionId, run.runId);
    const registry = service.readRegistry(meta.registryVersionId);
    expect(registry.state).toBe("WARNING"); expect(registry.canContinue).toBe(true); expect(registry.issues.some(i => i.severity === "ERROR")).toBe(true);
    const id = registry.selectableProcesses[0].processId;
    await service.runScore(service.openProcess(id).job!);
    const card = service.readProcess(id);
    expect(card.activeScoreSnapshot!.value.criteria.slice(0, 2).map(c => c.score)).toEqual([2, null]);
  });
  it("returns no fabricated selection for an empty compatible sheet", () => {
    const service = new RegistryService(temporary.store);
    const meta = service.upload(synthetic({ rows: {} }), "empty.xlsx");
    const run = service.selectSheet(meta.registryVersionId, "Лист3"); service.processSheet(meta.registryVersionId, run.runId);
    expect(service.readRegistry(meta.registryVersionId)).toMatchObject({ state: "VALID", canContinue: false, selectableProcesses: [] });
  });
  it("exposes each exact processing run and ignores the stale result of a same-sheet reselection", () => {
    const service = new RegistryService(temporary.store), registry = importOfficial(service);
    const ids = registry.selectableProcesses.map(p => p.processId);
    const old = service.selectSheet(registry.registryVersionId, "Лист3");
    const current = service.selectSheet(registry.registryVersionId, "Лист3");
    expect(old.view.processingRunId).toBe(old.runId);
    expect(current.runId).not.toBe(old.runId);
    service.processSheet(registry.registryVersionId, old.runId);
    expect(service.readRegistry(registry.registryVersionId)).toMatchObject({ processingRunId: current.runId, state: "READING", canContinue: false, selectableProcesses: [] });
    service.processSheet(registry.registryVersionId, current.runId);
    expect(service.readRegistry(registry.registryVersionId).selectableProcesses.map(p => p.processId)).toEqual(ids);
    expect(Object.keys(temporary.store.read().processes)).toHaveLength(6);
  });
  it("rejects invalid uploads before RegistryVersion creation", () => {
    const service = new RegistryService(temporary.store);
    expect(() => service.upload(new Uint8Array(), "bad.xlsx")).toThrow();
    expect(Object.keys(temporary.store.read().registries)).toHaveLength(0);
    expect(() => service.readProcess("not-found")).toThrow(expect.objectContaining({ code: "PROCESS_NOT_FOUND" }));
    expect(() => service.readSource("not-found")).toThrow(expect.objectContaining({ code: "SOURCE_NOT_FOUND" }));
  });
});
